# Generated by Django 5.0.1 on 2024-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='authors/'),
            preserve_default=False,
        ),
    ]
