# Generated by Django 5.0.1 on 2024-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_remove_author_title_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
