# Generated by Django 5.0.1 on 2024-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subarticle',
            old_name='footer_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='subarticle',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subarticle',
            name='header_content',
        ),
        migrations.AddField(
            model_name='subarticle',
            name='is_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='articles/comments/'),
        ),
    ]
