# Generated by Django 5.0.1 on 2024-01-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
