# Generated by Django 5.0.1 on 2024-01-27 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='archive.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='top_level_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
