# Generated by Django 5.0.1 on 2024-01-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_article_parent_article_top_level_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='article',
            name='top_level_parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='top_level_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
